strictness: high
test-warnings: true
doc-warnings: false

ignore-paths:
  - .git
  - docs
  - env

pep8:
  options:
    max-line-length: 100

pylint:
  disable:
    - unsubscriptable-object

pyflakes:
  disable:
    - F401

mccabe:
  run: true
